export const dynamic = 'force-dynamic';

/**
 * GET /api/calendar/export
 * Generates an .ics calendar file with all upcoming compliance events.
 */

import { createClient } from '@/utils/supabase/server';
import { NextRequest, NextResponse } from 'next/server';
import { getUser } from '@/utils/supabase/queries';

function escapeIcs(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/;/g, '\\;').replace(/,/g, '\\,').replace(/\n/g, '\\n');
}

function foldLine(line: string): string {
  // ICS spec: lines must be max 75 octets, folded with CRLF + space
  const chunks: string[] = [];
  while (line.length > 75) {
    chunks.push(line.slice(0, 75));
    line = ' ' + line.slice(75);
  }
  chunks.push(line);
  return chunks.join('\r\n');
}

function dateToIcs(dateStr: string): string {
  // Convert YYYY-MM-DD to YYYYMMDD (all-day event)
  return dateStr.replace(/-/g, '');
}

function nowToIcs(): string {
  return new Date().toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
}

const EVENT_TYPE_LABELS: Record<string, string> = {
  policy_review: 'Policy Review',
  training_renewal: 'Training Renewal',
  baa_renewal: 'BAA Renewal',
  risk_assessment: 'Risk Assessment',
  quarterly_review: 'Quarterly Review',
  mitigation_deadline: 'Mitigation Deadline',
  custom: 'Custom Event',
};

export async function GET(request: NextRequest) {
  try {
    const supabase = createClient();
    const user = await getUser(supabase);
    if (!user) return new NextResponse('Unauthorized', { status: 401 });

    const { data: org } = await supabase
      .from('organizations')
      .select('id, name')
      .eq('user_id', user.id)
      .single();
    if (!org) return new NextResponse('Organization not found', { status: 404 });

    const { data: events } = await (supabase as any)
      .from('compliance_calendar_events')
      .select('*')
      .eq('org_id', (org as any).id)
      .not('status', 'in', '("complete","cancelled")')
      .order('due_date', { ascending: true });

    const orgName = escapeIcs((org as any).name ?? 'HIPAA Hub');
    const now = nowToIcs();

    const lines: string[] = [
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      `PRODID:-//HIPAA Hub//Compliance Calendar//EN`,
      `X-WR-CALNAME:${orgName} — HIPAA Compliance`,
      'X-WR-TIMEZONE:UTC',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
    ];

    for (const event of events ?? []) {
      const typeLabel = EVENT_TYPE_LABELS[event.event_type] ?? event.event_type;
      const desc = `Type: ${typeLabel}\\nStatus: ${event.status}\\nGenerated by HIPAA Hub`;
      const dtStart = dateToIcs(event.due_date);
      // End date is next day for all-day events
      const dtEnd = event.end_date
        ? dateToIcs(event.end_date)
        : dateToIcs(
            new Date(new Date(event.due_date).getTime() + 86400000)
              .toISOString()
              .split('T')[0]
          );

      lines.push('BEGIN:VEVENT');
      lines.push(foldLine(`UID:${event.id}@hipaahubhealth.com`));
      lines.push(foldLine(`DTSTAMP:${now}`));
      lines.push(foldLine(`DTSTART;VALUE=DATE:${dtStart}`));
      lines.push(foldLine(`DTEND;VALUE=DATE:${dtEnd}`));
      lines.push(foldLine(`SUMMARY:${escapeIcs(event.title)}`));
      lines.push(foldLine(`DESCRIPTION:${escapeIcs(desc)}`));
      lines.push(foldLine(`CATEGORIES:${escapeIcs(typeLabel)}`));
      if (event.location) {
        lines.push(foldLine(`LOCATION:${escapeIcs(event.location)}`));
      }
      lines.push('END:VEVENT');
    }

    lines.push('END:VCALENDAR');

    const icsContent = lines.join('\r\n') + '\r\n';

    return new NextResponse(icsContent, {
      headers: {
        'Content-Type': 'text/calendar; charset=utf-8',
        'Content-Disposition': `attachment; filename="hipaa-compliance-calendar.ics"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (e) {
    console.error('[calendar/export GET]', e);
    return new NextResponse('Server error', { status: 500 });
  }
}
