import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';
import { getUser } from '@/utils/supabase/queries';

export async function GET(request: NextRequest) {
  try {
    const supabase = createClient();
    const user = await getUser(supabase);
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

    const { searchParams } = new URL(request.url);
    const recordId = searchParams.get('id');
    if (!recordId) return NextResponse.json({ error: 'Missing record ID' }, { status: 400 });

    // Fetch training record
    const { data: record, error } = await (supabase as any)
      .from('training_records')
      .select('*')
      .eq('id', recordId)
      .eq('user_id', user.id)
      .single();

    if (error || !record) {
      return NextResponse.json({ error: 'Training record not found' }, { status: 404 });
    }

    if (record.completion_status !== 'completed') {
      return NextResponse.json({ error: 'Training not completed' }, { status: 400 });
    }

    // Get org
    const { data: org } = await supabase
      .from('organizations')
      .select('name')
      .eq('user_id', user.id)
      .single();

    const { default: jsPDF } = await import('jspdf');
    const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

    const W = doc.internal.pageSize.getWidth();
    const H = doc.internal.pageSize.getHeight();

    // Border
    doc.setDrawColor(14, 39, 78);
    doc.setLineWidth(3);
    doc.rect(8, 8, W - 16, H - 16);
    doc.setLineWidth(1);
    doc.rect(12, 12, W - 24, H - 24);

    // Header bar
    doc.setFillColor(14, 39, 78);
    doc.rect(12, 12, W - 24, 20, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text('HIPAA HUB — COMPLIANCE TRAINING CERTIFICATE', W / 2, 25, { align: 'center' });

    // Title
    doc.setTextColor(14, 39, 78);
    doc.setFontSize(28);
    doc.setFont('helvetica', 'bold');
    doc.text('Certificate of Completion', W / 2, 58, { align: 'center' });

    // Subtitle
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(86, 86, 86);
    doc.text('This certifies that', W / 2, 72, { align: 'center' });

    // Name
    doc.setFontSize(26);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 39, 78);
    doc.text(record.full_name, W / 2, 92, { align: 'center' });

    // Underline
    const nameWidth = doc.getTextWidth(record.full_name);
    doc.setDrawColor(0, 188, 235);
    doc.setLineWidth(0.8);
    doc.line(W / 2 - nameWidth / 2, 95, W / 2 + nameWidth / 2, 95);

    // Module
    doc.setFontSize(13);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(86, 86, 86);
    doc.text('has successfully completed', W / 2, 108, { align: 'center' });

    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 188, 235);
    const moduleName = record.module_name || 'HIPAA Awareness Training';
    doc.text(moduleName, W / 2, 120, { align: 'center' });

    // Details row
    const completionDate = record.training_date
      ? new Date(record.training_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
      : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    const expirationDate = record.expiration_date
      ? new Date(record.expiration_date).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
      : 'N/A';

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(86, 86, 86);
    doc.text(`Completion Date: ${completionDate}`, W / 2 - 60, 137, { align: 'center' });
    doc.text(`Valid Through: ${expirationDate}`, W / 2 + 60, 137, { align: 'center' });
    if (record.quiz_score !== null && record.quiz_score !== undefined) {
      doc.text(`Quiz Score: ${record.quiz_score}%`, W / 2, 145, { align: 'center' });
    }

    // Signature section
    const sigY = 158;
    doc.setDrawColor(14, 39, 78);
    doc.setLineWidth(0.5);
    doc.line(W / 2 - 60, sigY, W / 2 - 10, sigY);
    doc.line(W / 2 + 10, sigY, W / 2 + 60, sigY);

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('Privacy Officer', W / 2 - 35, sigY + 5, { align: 'center' });
    doc.text('Security Officer', W / 2 + 35, sigY + 5, { align: 'center' });

    // Organization
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(14, 39, 78);
    doc.text(org?.name || 'Your Organization', W / 2, sigY + 14, { align: 'center' });

    // Footer
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 150, 150);
    doc.text(`Certificate ID: ${recordId} · Generated by HIPAA Hub · ${new Date().toLocaleDateString()}`, W / 2, H - 18, { align: 'center' });

    // Mark certificate as issued
    await (supabase as any)
      .from('training_records')
      .update({ certificate_issued: true, certificate_issued_at: new Date().toISOString() })
      .eq('id', recordId);

    const pdfBytes = doc.output('arraybuffer');
    const fileName = `HIPAA_Certificate_${record.full_name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;

    return new NextResponse(pdfBytes, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    console.error('Error generating certificate:', error);
    return NextResponse.json({ error: 'Failed to generate certificate' }, { status: 500 });
  }
}
